export default {
    "login": "metalhead5209",
    "id": 73142998,
    "node_id": "MDQ6VXNlcjczMTQyOTk4",
    "avatar_url": "https://avatars.githubusercontent.com/u/73142998?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/metalhead5209",
    "html_url": "https://github.com/metalhead5209",
    "followers_url": "https://api.github.com/users/metalhead5209/followers",
    "following_url": "https://api.github.com/users/metalhead5209/following{/other_user}",
    "gists_url": "https://api.github.com/users/metalhead5209/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/metalhead5209/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/metalhead5209/subscriptions",
    "organizations_url": "https://api.github.com/users/metalhead5209/orgs",
    "repos_url": "https://api.github.com/users/metalhead5209/repos",
    "events_url": "https://api.github.com/users/metalhead5209/events{/privacy}",
    "received_events_url": "https://api.github.com/users/metalhead5209/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Aaron Rodi",
    "company": null,
    "blog": "http://aaron-rodi.netlify.app/",
    "location": "Lafayette, LA",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": "a_wodi",
    "public_repos": 32,
    "public_gists": 0,
    "followers": 10,
    "following": 17,
    "created_at": "2020-10-19T22:18:05Z",
    "updated_at": "2022-09-08T09:37:44Z"
  }